use customer;
show tables;

select * from customer_table
limit 10;
# what is the total revenue generated by male vs female cutomer
select gender ,sum(purchase_amount) as total_revenue
from customer_table
group by gender;

#which customer used a discoun but still spent more than average purchase amount
select customer_id, purchase_amount
from customer_table
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_table);

# which are the top 5 highest average review rating
select item_purchased ,round(avg(review_rating),2) as average_product_rating
from customer_table
group by item_purchased
order by avg(review_rating) desc
limit 5;

# compare the average purchase amunts between standard and express shipping 
select shipping_type,
round(avg(purchase_amount),2)
from customer_table
where shipping_type in ('Standard','Express')
group by shipping_type;

# do subscribed customer spend more? 
-- compare average spend and total revenue between sucriber and non-subscriber

select subscription_status,
count(customer_id) as total_customer, 
round(avg(purchase_amount),2) as avg_purchase_amount,
sum(purchase_amount) as total_revenue
from customer_table
where subscription_status in ('Yes','No')
group by subscription_status
;

# top 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2)  as discount_rate
from customer_table
group by item_purchased
order by discount_rate desc
limit 5;

# segment customer into new ,returning ,and loyal based on their total 
# number of previous purchases and show count of each segment

with customer_type as(
select customer_id ,previous_purchases ,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_table
)
select customer_segment ,count(*) as 'Number of customer'
from customer_type
group by customer_segment;

# what are the top 3 most purchased products within each category
with item_count as (
select category ,
item_purchased,
count(customer_id) as total_orders,
Row_Number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_table 
group by category ,item_purchased 
)
select item_rank,category ,item_purchased,total_orders
from item_count
where item_rank <= 3;

-- select item_rank,category ,item_purchased,total_orders
-- from (
-- select category ,item_purchased,
-- count(customer_id) as total_orders,
-- row_number() over (partition by category order by count(customer_id) desc) as item_rank
-- from customer_table 
-- group by category,item_purchased
-- ) as ranked_iem 
-- where item_rank <= 3;

-- customer who are repeat buyer (more than 5 previous purchase ) also likely to subscribe 
select subscription_status ,count(customer_id) as repeat_buyers
from customer_table 
where previous_purchases >= 5
group by subscription_status;

# revenue contribution of each age group 
select age_group ,
sum(purchase_amount) as total_revenue
from customer_table 
group by age_group 
order by total_revenue desc;

